posts/blueprint.py
from flask import Blueprint, render_template, request, abort,redirect
from flask_security import current_user

from models import Post, Image, Comment
from utils import access
from .create import create_comment
from .edit import edit_comment_by_id
from .forms import create_comment_form

posts = Blueprint('posts', __name__,
                  template_folder='templates',
                  static_folder='static'
                  )


@posts.route('/<post_id>/', methods=["GET", "POST"])
def read_post(post_id):
    errors = []

    # search post
    post = Post.query.filter(Post.id == int(post_id)).first()

    if not post:
        abort(404)

    # EDIT COMMENT
    edit = request.args.get("edit")
    print(request.data)
    if edit:
        errors, args = edit_comment_by_id(errors, edit)

        if errors:
            return render_template("wrong.html", errors=errors,
                                   request=request, access=access)
        form = args["form"]



    # CREATE COMMENT
    else:

        form = create_comment_form()

        args = {
            "post_id": post.id,
            "author_id": current_user.id
        }

        # add comment

        if request.method == "POST":
            errors = create_comment(errors, form, args)
            if not errors:
                return redirect(request.url)

    # PRINT ERRORS
    if errors:
        return render_template("wrong.html",
                               errors=errors,
                               request=request,
                               access=access)

    # GET COMMENTS FROM DB
    comments = (Comment.query
                .filter(Comment.post_id == post_id)
                .order_by(Comment.created.desc())
                )

    # GET IMAGES
    images = Image.query.filter(Image.post_id == post_id).all()

    return render_template("posts/post.html",
                           errors=errors,
                           post=post,
                           form=form,
                           access=access,
                           images=images,
                           comments=comments,
                           edit=edit
                           )

posts/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}Create post{% endblock %}


{% block main %}
    <form action="{{ url_for("create_item",item_type="post") }}" method="post" enctype="multipart/form-data">

        <p>Title</p>
        {{ form.title }}

        <p><br>Text</p>
        {{ form.text }}

        <p><br>Tags</p>
        {{ form.tags }}

        <p><br>Images</p>
        {{ form.images }}

        <button type="submit">Create Post</button>
    </form>
    <br>
    {% if not errors %}
        <p>all ok</p>
    {% endif %}

    {% for error in errors %}
        <p>{{ error }}</p>
    {% endfor %}

{% endblock %}

posts/templates/posts/create_tag.html
{% extends "base.html" %}
{% block title %}Create tag{% endblock %}


{% block main %}

<form action="{{ url_for("create_item",item_type="tag") }}" method="post">
    <p>Tag's name</p>
    {{ form.name }}
    
    <button type="submit">Create Tag</button>
</form>
    <br>
{% if not errors %}
    <p>all ok</p>
{% endif %}

{% for error in errors %}
    <p>{{ error }}</p>
{% endfor %}

{% endblock %}

posts/templates/posts/edit_post.html
{% extends "base.html" %}
{% block title %}Edit post{% endblock %}


{% block main %}

    <form action="{{ url_for("edit_item",item_type="post",item_id=item_id) }}"
          method="post" enctype="multipart/form-data">

        <p>Title</p>
        {{ args["form"].title }}

        <p><br>Text</p>
        {{ args["form"].text }}

        <p><br>Tags</p>
        {{ args["form"].tags }}

        <p><br>Images</p>
        {{ args["form"].images }}

        <button type="submit">Save</button>
    </form>
    <br>
    {% if not errors %}
        <p>all ok</p>
    {% endif %}

    {% for error in errors %}
        <p>{{ error }}</p>
    {% endfor %}

    {% for image in args["images"] %}
        <img src="{{ "/"+image.address }}" alt="{{ image.id }}">
        <form action="{{ url_for("delete_item",item_type="image",item_id = image.id) }}" method="POST">
            <button type="submit">Delete image</button>
        </form>
    {% endfor %}

{% endblock %}

posts/templates/posts/edit_tag.html
{% extends "base.html" %}
{% block title %}Edit tag{% endblock %}


{% block main %}
    <form action="{{ url_for("edit_item",item_type="tag",item_id=item_id) }}" method="post">

        <p>Name</p>
        {{ args["form"].name }}

        <button type="submit">Save</button>
    </form>
    <br>
    {% if not errors %}
        <p>all ok</p>
    {% endif %}

    {% for error in errors %}
        <p>{{ error }}</p>
    {% endfor %}

{% endblock %}

posts/templates/posts/post.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for("posts.static",filename = "posts/post.css") }}">
{% endblock %}


{% block main %}

    <!-- POST -------------------------------------------------------------------------------------------------------->

    <div class="post">

        <p>{{ post.text }}</p>
        <ul>
            {% for tag in post.tags %}
                <li>
                    <a href="{{ url_for("list_items",item="post",tag=tag.name) }}">{{ tag.name }}</a>
                </li>
            {% endfor %}
        </ul>

        {% for image in images %}
            <img src="{{ "/"+image.address }}" alt="{{ image.id }}">
        {% endfor %}

    </div>


    <!-- COMMENTS ---------------------------------------------------------------------------------------------------->

    <div class="comments">{#  Comment form   #}
        <div class="create_comment"><h3>Comments</h3>
            {% if current_user.is_authenticated %}
                <form action="{{ url_for("posts.read_post",post_id = post.id,edit=edit) }}" method="post">

                    {{ form.text }}

                    <button type="submit">Comment</button>
                </form>
            {% endif %}</div>

        {#  Comments #}

        <ul>

            {% for comment in comments %}
                <li>
                    {#  Comment #}

                    <h4>{{ comment.author.email }}</h4>
                    <br>

                    <p>{{ comment.text }}</p>
                    <br>

                    {# button delete and edit for author and moderator #}
                    {% if access(["moder"],author = comment.author) %}

                        <form action="{{ url_for("delete_item",item_type="comment",item_id = comment.id) }}"
                              method="post">
                            <button type="submit">Delete</button>
                        </form>

                    {% endif %}
                    {% if access(author = comment.author) %}

                        <a href="{{ url_for("posts.read_post",post_id = comment.post_parent.id,edit=comment.id) }}">
                            <button type="submit">Edit</button>
                        </a>

                    {% endif %}
                    <p>{{ comment.created }}</p>
                </li>
            {% endfor %}

        </ul>
    </div>

{% endblock %}

posts/templates/posts/post_in_list.html
<div class="pages__item-title">
    <h3>
        <a href="{{ url_for("posts.read_post",post_id=item.id) }}">{{ item.title }}</a>

        <br>
    </h3>
</div>

<div class="pages__item-preview">
    <a href="{{ url_for("posts.read_post",post_id=item.id) }}">{{ item.text }}</a>
</div>


<div class="pages__item-form">

    {% if access(author=item.author) %}
        <form action="{{ url_for("edit_item",item_type="post",item_id=item.id) }}">
            <button>Edit post</button>
        </form>
    {% endif %}

    {% if access(["moder"],item.author) %}
        <form action="{{ url_for("delete_item",item_type="post",item_id=item.id) }}" method="post">
            <button type="submit">delete post</button>
        </form>
    {% endif %}

</div>

<div class="pages__item-author">
    Author:<a href="#">{{ item.author.email }}</a> <br>
</div>
<div class="pages__item_data">
    {{ item.created }}
</div>

posts/templates/posts/tag_in_list.html
<div class="pages__item-name">
    Tag name: <a href="{{ url_for("list_items",item="post",tag=item.name) }}">{{ item.name }}</a>
</div>

<div class="pages__item-form">
    {% if access(["moder"]) %}
        <form action="{{ url_for("edit_item",item_type="tag",item_id=item.id) }}">
            <button>Edit tag</button>
        </form>

        <form action="{{ url_for("delete_item",item_type="tag",item_id=item.id) }}" method="post">
            <button type="submit">Delete tag</button>
        </form>
    {% endif %}
</div>